language: objective-c
os: osx
osx_image: xcode11.2
branches:
  only:
    - master
cache:
  timeout: 86400
  directories:
    - $HOME/unity_download_cache/ #Cache unity installer files
    - $HOME/project_cache/ #Cache for created unity projects
before_install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/coryleach/UnityTravisCI/master/bin/before-install.sh)
install:
  - ./clean-project.sh
  - ./install.sh
  - source ./find-unity.sh #source this because it exports required env vars
before_script:
  - ./get-license.sh
script:
  - source ./setup-project.sh #source this because it exports project path
  - ./run-tests.sh
after_success:
  - ./return-license.sh
  - ./clean-project.sh
after_failure:
  - ./return-license.sh
  - ./clean-project.sh

